#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2021 Arm Limited.
# SPDX-License-Identifier: Apache-2.0
#

import os
import common

Import("env")

common.setup_common_env(env)

env.Alias(
    "install",
    env.Install(
        os.path.join(env["install_include_dir"], "ethosn_utils"),
        Glob(os.path.join("include", "ethosn_utils", "*")),
    ),
)

# Build unit tests, if requested.
if env["tests"]:
    SConscript(dirs="tests", duplicate=False, exports=["env"])
