#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2022 Arm Limited.
# SPDX-License-Identifier: Apache-2.0
#

import common

Import("env")

common.setup_common_env(env)
common.setup_toolchain(env, env["platform"])
common.setup_sanitize(env)
install_dir = env["install_include_dir"] + "/ethosn_command_stream"

env.Install(install_dir, Glob("include/ethosn_command_stream/*.hpp"))
env.Install(install_dir + "/cascading", Glob("include/ethosn_command_stream/cascading/*.hpp"))
env.Alias("install", install_dir)

if env["tests"]:
    SConscript(dirs="tests", duplicate=False, exports="env")
