#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2021 Arm Limited. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

import os
import common

Import('env')

common.setup_common_env(env)
common.setup_toolchain(env, env['platform'])

env.Alias('install', env.Install(os.path.join(env['install_include_dir'], 'ethosn_command_stream'),
                                 Glob(os.path.join('include', 'ethosn_command_stream', '*'))))

if env['tests']:
    SConscript(dirs='tests', duplicate=False, exports='env')
