//
// Copyright © 2023 Arm Limited.
// SPDX-License-Identifier: Apache-2.0
//
// Contains the binaries of the PLE kernels and a lookup showing where each kernel is.
// This is in its own cpp file to avoid having to recompile it
// as much (it can take a good few seconds).

#include <cstdint>
#include <utility>

#include <ethosn_command_stream/PleKernelIds.hpp>

namespace ethosn
{
namespace control_unit
{

// The actual data is generated by the PLE build system, so we simply include it here.
// When targetting the hardware, mark it with a section attribute so that the
// scatter file can place it in a specific location, otherwise no attributes are needed.
#if defined(CONTROL_UNIT_HARDWARE)
#define PLE_KERNEL_BINARIES_ATTRIBUTES __attribute__((used, section("PLE_DATA")))
#else
#define PLE_KERNEL_BINARIES_ATTRIBUTES
#endif

#include <ethosn_ple/PleKernelBinaries.hpp>

}    // namespace control_unit
}    // namespace ethosn
