#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2023 Arm Limited.
# SPDX-License-Identifier: Apache-2.0
#

# Top level build script for Ethos-N driver stack
# - reuse variable definitions across sub-module builds
# - remove duplication

from __future__ import print_function
import os
from SCons.Node.Alias import default_ans
import common


Help(
    """
Usage:
    See README.md and the Software Integration guide.

Variables:
"""
)

var = common.create_variables()

var.AddVariables(
    BoolVariable("debug", "Build in debug instead of release mode", False),
    BoolVariable("tests", "Build UnitTests. Use target 'unit-tests' to execute", False),
    EnumVariable(
        "asserts",
        "Enable asserts. 'debug' means it is enabled if 'debug=1'",
        "debug",
        allowed_values=("0", "1", "debug"),
    ),
    EnumVariable(
        "logging",
        "Build with logging support. 'debug' means it is enabled if 'debug=1'",
        "debug",
        allowed_values=("0", "1", "debug"),
    ),
    BoolVariable("sanitize", "Build with sanitizers for gcc", False),
    EnumVariable(
        "platform",
        "Build for a given platform.",
        "native",
        allowed_values=("native", "aarch64"),
    ),
    PathVariable("build_dir", "Build output directory", "build", PathVariable.PathIsDirCreate),
    ("device_node_prefix", "Device node prefix in the dev filesystem", "/dev/ethosn"),
    ("device_node_base_id", "Valid device node identifier in the dev filesystem", "0"),
    (
        "firmware_profiling_node",
        "Firmware profiling node in the sys filesystem",
        "/sys/kernel/debug/ethosn0/core0/firmware_profiling",
    ),
    BoolVariable(
        "disable_large_winograd",
        "Prevent the support library generating command streams containing large (>=7x7) kernel sizes with winograd.",
        False,
    ),
    BoolVariable(
        "allow_command_stream_dump",
        "Build the driver library with the ability to dump command streams. "
        "This requires additional build-time dependencies.",
        False,
    ),
    BoolVariable("werror", "Build with -Werror", True),
    PathVariable(
        "unit_test_kernel_dir",
        "Path to the Linux kernel source tree used when building the unit tests.",
        "",
        PathVariable.PathAccept,
    ),
    PathVariable(
        "armnn_dir",
        "Directory of the Arm NN source code to use for full-stack testing and system tests.",
        "",
        PathVariable.PathAccept,
    ),
    PathVariable(
        "cmsis_dir",
        "Path to the CMSIS core include path used when building the firmware.",
        "",
        PathVariable.PathAccept,
    ),
    BoolVariable("profiling", "Enable performance profiling", False),
)

env = Environment(variables=var)

Help(var.GenerateHelpText(env))
# Parse the default variables which were setup by common.create_variables()
common.parse_default_vars(env)

# Top level assumes knowledge of the different components locations
env["driver_library_dir"] = "driver_library"
env["support_library_dir"] = "support_library"
env["command_stream_dir"] = os.path.join(env["support_library_dir"], "command_stream")
env["utils_dir"] = "utils"
env["lib_xml_to_binary_dir"] = os.path.join(env["command_stream_dir"], "xml_to_binary")
env["system_tests_dir"] = os.path.join("..", "tools", "system_tests")
env["control_unit_dir"] = os.path.join("..", "firmware", "control_unit")
env["ple_dir"] = os.path.join("..", "firmware", "ple")

# These can be overridden by developer options, if applicable
env["kernel_module_dir"] = os.path.join("..", "kernel-module")
env["target"] = "kmod"
env["force_ple_fault"] = False
env["ple_logging"] = "off"
env["arch_regs_dir"] = os.path.join("..", "firmware", "include")
env["ple_cluster_build"] = False
env["disable_Pow2"] = False

# Because these path arguments may be relative, they must be correctly interpreted as relative to the top-level
# folder rather than the 'build' subdirectory, which is what scons would do if they were passed to the SConscript
# files as-is. Therefore we convert them to absolute paths here, where they will be interpreted correctly.
common.abs_path(
    env,
    [
        "command_stream_dir",
        "driver_library_dir",
        "support_library_dir",
        "utils_dir",
        "lib_xml_to_binary_dir",
        "kernel_module_dir",
        "system_tests_dir",
        "control_unit_dir",
        "ple_dir",
        "arch_regs_dir",
        "cmsis_dir",
    ],
)

if env["armnn_dir"]:
    common.abs_path(env, ["armnn_dir"])

# Avoid building extra components by default, e.g. libXmlToBinary
Default(
    common.get_driver_library_build_dir(env),
    common.get_support_library_build_dir(env),
    common.get_command_stream_build_dir(env),
)

optional_var = ""
optional_dir = ""
if (common.load_optional(env)):
    optional_dir = env["optional_dir"]
    optional_var = env["optional_var"]

if (optional_var):
    env[optional_var] = optional_dir

# Process all modules which use a variant_dir
# We're going to clone this, in the current form, some modules are polluting the env, breaking subsequent builds.
env_backup = env

# PLE kernels are always compiled in release mode, PLE debugging is not supported
env = env_backup.Clone()
env["debug"] = False
SConscript(
    dirs=env["ple_dir"],
    variant_dir=common.get_ple_build_dir(env),
    duplicate=False,
    exports="env",
)

Export("env")
common.load_extras(env_backup)

env = env_backup.Clone()
SConscript(
    dirs=[env["driver_library_dir"]],
    variant_dir=common.get_driver_library_build_dir(env),
    duplicate=False,
    exports="env",
)

env = env_backup.Clone()
SConscript(
    dirs=[env["support_library_dir"]],
    variant_dir=common.get_support_library_build_dir(env),
    duplicate=False,
    exports="env",
)

env = env_backup.Clone()
SConscript(
    dirs=[env["command_stream_dir"]],
    variant_dir=common.get_command_stream_build_dir(env),
    duplicate=False,
    exports="env",
)

env = env_backup.Clone()
SConscript(
    dirs=[env["utils_dir"]],
    variant_dir=common.get_utils_build_dir(env),
    duplicate=False,
    exports="env",
)

env = env_backup.Clone()
SConscript(
    dirs=[env["lib_xml_to_binary_dir"]],
    variant_dir=common.get_lib_xml_to_binary_build_dir(env),
    duplicate=False,
    exports="env",
)

if env["tests"]:
    # System Test uses Catch2 framework. If tests has been disabled, dont build system tests
    env = env_backup.Clone()
    SConscript(
        dirs=env["system_tests_dir"],
        variant_dir=common.get_system_tests_build_dir(env),
        duplicate=False,
        exports="env",
    )

env = env_backup.Clone()  # making sure we're starting with a clean config
variant_dir = common.get_control_unit_build_dir(env, "hardware")
# Create aliases for the hardware targets so you can run:
# scons control_unit-hardware
Alias(["control_unit-all", "control_unit-hardware"], variant_dir)
env["backend"] = "hardware"
SConscript(
    dirs=env["control_unit_dir"],
    variant_dir=variant_dir,
    duplicate=False,
    exports="env",
)

aliases = default_ans.keys()
env.Help("\n")
env.Help("Found targets: \n")
for alias in sorted(aliases):
    env.Help("    {}\n".format(alias))
