#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2021,2023 Arm Limited.
# SPDX-License-Identifier: Apache-2.0
#

import os

Import("env")

srcs = Glob("*.cpp") + env.Object(Glob("cpp17/*.cpp"), CXXSTD="c++17")

unitTests = env.Program("UnitTests", srcs)
testAlias = env.Alias("utils-unit-tests", [unitTests], unitTests[0].abspath)
env.Alias("unit-tests", testAlias)
AlwaysBuild(testAlias)
