[package]
name = "profiling_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.16"
clap = { version= "4.3.19", features = ["derive"] }
serde_json = "1.0.103"